### PR TITLE
Fixed path to client install check

### PR DESCRIPTION
**Pull request by nmaludy**
@paxri01 can you check this file exists in RHEL7, also if you run `ipa-client-install --uninstall --unattended` it appears to go away in RHEL 8, can you confirm that as well?

### CODE REVIEW

**Comment by paxri01** [comment]
Which file `ipa-client-install` (comes from ipa-client package on both RHEL 7/8)

**Comment by paxri01** [comment]
> @paxri01 on RHEL 8 `/var/lib/ipa-client/sysrestore/sysrestore.state` is created when `ipa-client-install` succeeds, i was curious if it was the same on RHEL 7.
> 
> Then if you do `ipa-client-install --uninstall --unattended` the file `/var/lib/ipa-client/sysrestore/sysrestore.state` is gone.
> 
> On RHEL 8, `/etc/ipa/default.conf` no longer exists.

`[14:51:14 root@rhel8-test01 /etc/ipa] 
> ls -l
total 8
-rw-r--r--. 1 root root 1322 Oct 29 10:08 ca.crt
-rw-r--r--. 1 root root  306 Oct 29 10:08 default.conf
drwxr-xr-x. 2 root root   74 Sep 23 13:42 nssdb
`

**Comment by nmaludy** [comment]
Re-testing on my end. MIght have been because i had a jacked up autmount config (now fixed). I do see /etc/ipa/defaults.conf, but want to test on a fresh host end-to-end.

**Comment by nmaludy** [comment]
@paxri01 you were right, must have been my automount blunder breaking things

**Pull request closed without merging**
